### ISSUE TITLE
NVIDIA RTX 5070 with CUDA 12.8 (sm_120), Error Message

### ISSUE THREAD

**Issue by adventure705** [RVC-Boss/GPT-SoVITS#2192]
I am using an NVIDIA RTX 5070 with CUDA 12.8 (sm_120). 
Previously, PyTorch was not compatible, but a preview (Nightly) version was released yesterday, so I updated PyTorch.
However, after updating PyTorch, when running inference_webui.py, the following error occurs.

Running on local URL:  http://0.0.0.0:9874
"C:\Users\sky2311\GPT-SoVITS\runtime\python.exe" GPT_SoVITS/inference_webui.py
C:\Users\sky2311\GPT-SoVITS\runtime\lib\site-packages\transformers\utils\generic.py:441: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
C:\Users\sky2311\GPT-SoVITS\runtime\lib\site-packages\transformers\utils\generic.py:309: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
DEBUG:torio._extension.utils:Loading FFmpeg6
DEBUG:torio._extension.utils:Failed to load FFmpeg6 extension.
Traceback (most recent call last):
  File "C:\Users\sky2311\GPT-SoVITS\runtime\lib\site-packages\torio\_extension\utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "C:\Users\sky2311\GPT-SoVITS\runtime\lib\site-packages\torio\_extension\utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "C:\Users\sky2311\GPT-SoVITS\runtime\lib\site-packages\torio\_extension\utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File "C:\Users\sky2311\GPT-SoVITS\runtime\lib\site-packages\torch\_ops.py", line 1392, in load_library
    ctypes.CDLL(path)
  File "ctypes\__init__.py", line 374, in __init__
FileNotFoundError: Could not find module 'C:\Users\sky2311\GPT-SoVITS\runtime\Lib\site-packages\torio\lib\libtorio_ffmpeg6.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
DEBUG:torio._extension.utils:Loading FFmpeg5
DEBUG:torio._extension.utils:Failed to load FFmpeg5 extension.
Traceback (most recent call last):
  File "C:\Users\sky2311\GPT-SoVITS\runtime\lib\site-packages\torio\_extension\utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "C:\Users\sky2311\GPT-SoVITS\runtime\lib\site-packages\torio\_extension\utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "C:\Users\sky2311\GPT-SoVITS\runtime\lib\site-packages\torio\_extension\utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File "C:\Users\sky2311\GPT-SoVITS\runtime\lib\site-packages\torch\_ops.py", line 1392, in load_library
    ctypes.CDLL(path)
  File "ctypes\__init__.py", line 374, in __init__
FileNotFoundError: Could not find module 'C:\Users\sky2311\GPT-SoVITS\runtime\Lib\site-packages\torio\lib\libtorio_ffmpeg5.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
DEBUG:torio._extension.utils:Loading FFmpeg4
DEBUG:torio._extension.utils:Failed to load FFmpeg4 extension.
Traceback (most recent call last):
  File "C:\Users\sky2311\GPT-SoVITS\runtime\lib\site-packages\torio\_extension\utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "C:\Users\sky2311\GPT-SoVITS\runtime\lib\site-packages\torio\_extension\utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "C:\Users\sky2311\GPT-SoVITS\runtime\lib\site-packages\torio\_extension\utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File "C:\Users\sky2311\GPT-SoVITS\runtime\lib\site-packages\torch\_ops.py", line 1392, in load_library
    ctypes.CDLL(path)
  File "ctypes\__init__.py", line 374, in __init__
FileNotFoundError: Could not find module 'C:\Users\sky2311\GPT-SoVITS\runtime\Lib\site-packages\torio\lib\libtorio_ffmpeg4.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
DEBUG:torio._extension.utils:Loading FFmpeg
DEBUG:torio._extension.utils:Failed to load FFmpeg extension.
Traceback (most recent call last):
  File "C:\Users\sky2311\GPT-SoVITS\runtime\lib\site-packages\torio\_extension\utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "C:\Users\sky2311\GPT-SoVITS\runtime\lib\site-packages\torio\_extension\utils.py", line 106, in _find_versionsed_ffmpeg_extension
    raise RuntimeError(f"FFmpeg{version} extension is not available.")
RuntimeError: FFmpeg extension is not available.
Traceback (most recent call last):
  File "C:\Users\sky2311\GPT-SoVITS\GPT_SoVITS\inference_webui.py", line 63, in <module>
    from AR.models.t2s_lightning_module import Text2SemanticLightningModule
  File "C:\Users\sky2311\GPT-SoVITS\GPT_SoVITS\AR\models\t2s_lightning_module.py", line 11, in <module>
    from AR.models.t2s_model import Text2SemanticDecoder
  File "C:\Users\sky2311\GPT-SoVITS\GPT_SoVITS\AR\models\t2s_model.py", line 21, in <module>
    from AR.modules.transformer import LayerNorm
  File "C:\Users\sky2311\GPT-SoVITS\GPT_SoVITS\AR\modules\transformer.py", line 13, in <module>
    from AR.modules.activation import MultiheadAttention
  File "C:\Users\sky2311\GPT-SoVITS\GPT_SoVITS\AR\modules\activation.py", line 15, in <module>
    from AR.modules.patched_mha_with_cache import multi_head_attention_forward_patched
  File "C:\Users\sky2311\GPT-SoVITS\GPT_SoVITS\AR\modules\patched_mha_with_cache.py", line 41, in <module>
    ) -> Tuple[Tensor, Optional[Tensor]]:
NameError: name 'Tuple' is not defined

Could you help me find a solution?

(For reference, before updating PyTorch, I was encountering a different error, as shown below.)
"C:\Users\sky2311\GPT-SoVITS\runtime\python.exe" GPT_SoVITS/inference_webui.py
C:\Users\sky2311\GPT-SoVITS\runtime\lib\site-packages\torch\cuda\__init__.py:173: UserWarning:
NVIDIA GeForce RTX 5070 with CUDA capability sm_120 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_61 sm_70 sm_75 sm_80 sm_86 sm_90 compute_37.
If you want to use the NVIDIA GeForce RTX 5070 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))

**Comment by XXXXRT666** [comment]
PyTorch is still not compatible in your env

**Comment by mikekknd** [comment]
Similar problem with 5090 even with the update on nightly PyTorch. Spam a full screen of FATAL: this function is for sm80, but was built for sm370

**Comment by Ventery** [comment]
https://github.com/RVC-Boss/GPT-SoVITS/issues/2026

**Comment by adventure705** [comment]
I followed the instructions from #2026, but instead of using WSL2, I ran it directly on Windows. As of March 17, 2025, PyTorch has released a nightly version compatible with cu128, which allowed me to proceed.

I modified the code in the same way and ensured the folder paths were correct. Even after that, I encountered a few issues, but I was able to resolve them by modifying the weights_only=False part in the s2_train.py file.

There were some other minor problems, but I resolved them by asking ChatGPT (I don’t remember every single step). 
I still see warning messages, but since the results are coming out as expected, I am using it without any major issues.

My setup:

OS: Windows 11
GPU: NVIDIA RTX 5070
CUDA: 12.8
Python: 3.10

**Comment by lsdlh** [comment]
> I followed the instructions from [#2026](https://github.com/RVC-Boss/GPT-SoVITS/issues/2026), but instead of using WSL2, I ran it directly on Windows. As of2025年3月17日, PyTorch has released a nightly version compatible with cu128, which allowed me to proceed.我按照  [#2026](https://github.com/RVC-Boss/GPT-SoVITS/issues/2026)  的说明操作了，但没有使用 WSL2，而是直接在 Windows 上运行。截至 2025 年 3 月 17 日，PyTorch 已发布与 cu128 兼容的夜间版，这使我得以继续进行。
> 
> I modified the code in the same way and ensured the folder paths were correct. Even after that, I encountered a few issues, but I was able to resolve them by modifying the weights_only=False part in the s2_train.py file.我以同样的方式修改了代码，并确保文件夹路径正确。即便如此，我还是遇到了一些问题，但通过修改 s2_train.py 文件中的 weights_only=False 部分，我得以解决这些问题。
> 
> There were some other minor problems, but I resolved them by asking ChatGPT (I don’t remember every single step).还有一些其他的小问题，但我通过询问 ChatGPT 解决了它们（我不记得每一个具体步骤了）。 I still see warning messages, but since the results are coming out as expected, I am using it without any major issues.我仍然能看到警告信息，但由于结果如预期般呈现，所以目前使用起来没有出现什么大问题。
> 
> My setup: 我的设置:
> 
> OS: Windows 11 操作系统:Windows 11 GPU: NVIDIA RTX 5070 显卡：英伟达 RTX 5070 CUDA: 12.8 CUDA: 12。8 Python: 3.10

可以发一份改过的代码吗

**Comment by adventure705** [comment]
> > I followed the instructions from [#2026](https://github.com/RVC-Boss/GPT-SoVITS/issues/2026), but instead of using WSL2, I ran it directly on Windows. As of2025年3月17日, PyTorch has released a nightly version compatible with cu128, which allowed me to proceed.我按照  [#2026](https://github.com/RVC-Boss/GPT-SoVITS/issues/2026)  的说明操作了，但没有使用 WSL2，而是直接在 Windows 上运行。截至 2025 年 3 月 17 日，PyTorch 已发布与 cu128 兼容的夜间版，这使我得以继续进行。
> > I modified the code in the same way and ensured the folder paths were correct. Even after that, I encountered a few issues, but I was able to resolve them by modifying the weights_only=False part in the s2_train.py file.我以同样的方式修改了代码，并确保文件夹路径正确。即便如此，我还是遇到了一些问题，但通过修改 s2_train.py 文件中的 weights_only=False 部分，我得以解决这些问题。
> > There were some other minor problems, but I resolved them by asking ChatGPT (I don’t remember every single step).还有一些其他的小问题，但我通过询问 ChatGPT 解决了它们（我不记得每一个具体步骤了）。 I still see warning messages, but since the results are coming out as expected, I am using it without any major issues.我仍然能看到警告信息，但由于结果如预期般呈现，所以目前使用起来没有出现什么大问题。
> > My setup: 我的设置:
> > OS: Windows 11 操作系统:Windows 11 GPU: NVIDIA RTX 5070 显卡：英伟达 RTX 5070 CUDA: 12.8 CUDA: 12。8 Python: 3.10
> 
> 可以发一份改过的代码吗

Code link -> https://bit.ly/4hcKNWY 

I’m sharing the modified code file.

In addition to the changes explained in #2026, I made some additional modifications.
Not all changes are explicitly documented in detail.
Inside the shared file, any section labeled [코드수정] is something I modified based on ChatGPT’s suggestions.
I’m not entirely sure if those changes directly resolved the issue, but I included them anyway.

**Comment by lsdlh** [comment]
> > > I followed the instructions from [#2026](https://github.com/RVC-Boss/GPT-SoVITS/issues/2026), but instead of using WSL2, I ran it directly on Windows. As of2025年3月17日, PyTorch has released a nightly version compatible with cu128, which allowed me to proceed.我按照  [#2026](https://github.com/RVC-Boss/GPT-SoVITS/issues/2026)  的说明操作了，但没有使用 WSL2，而是直接在 Windows 上运行。截至 2025 年 3 月 17 日，PyTorch 已发布与 cu128 兼容的夜间版，这使我得以继续进行。
> > > I modified the code in the same way and ensured the folder paths were correct. Even after that, I encountered a few issues, but I was able to resolve them by modifying the weights_only=False part in the s2_train.py file.我以同样的方式修改了代码，并确保文件夹路径正确。即便如此，我还是遇到了一些问题，但通过修改 s2_train.py 文件中的 weights_only=False 部分，我得以解决这些问题。
> > > There were some other minor problems, but I resolved them by asking ChatGPT (I don’t remember every single step).还有一些其他的小问题，但我通过询问 ChatGPT 解决了它们（我不记得每一个具体步骤了）。 I still see warning messages, but since the results are coming out as expected, I am using it without any major issues.我仍然能看到警告信息，但由于结果如预期般呈现，所以目前使用起来没有出现什么大问题。
> > > My setup: 我的设置:
> > > OS: Windows 11 操作系统:Windows 11 GPU: NVIDIA RTX 5070 显卡：英伟达 RTX 5070 CUDA: 12.8 CUDA: 12。8 Python: 3.10
> > 
> > 
> > 可以发一份改过的代码吗
> 
> Code link(s2_train) -> https://bit.ly/4hcKNWY代码链接（s2_train） -> https://bit.ly/4hcKNWY
> 
> I’m sharing the modified code file.我正在分享修改后的代码文件。
> 
> In addition to the changes explained in [#2026](https://github.com/RVC-Boss/GPT-SoVITS/issues/2026), I made some additional modifications. Not all changes are explicitly documented in detail.并非所有变更都详细明确地记录在案。 Inside the shared file, any section labeled [코드수정] is something I modified based on ChatGPT’s suggestions.在共享文件中，任何标有 [코드수정] 的部分都是我根据 ChatGPT 的建议修改的内容。 I’m not entirely sure if those changes directly resolved the issue, but I included them anyway.我不太确定那些改动是否直接解决了问题，但还是把它们加进去了。除了在  [#2026](https://github.com/RVC-Boss/GPT-SoVITS/issues/2026)  中解释的那些改动之外，我还做了一些额外的修改。

Thanks a lot.

**Comment by hofbauermarketing** [comment]
Hey guys, i saw it is already solved, i am interesting in using MuseTalks with my 5070ti but always get the error code:

Spam a full screen of FATAL: this function is for sm80, but was built for sm370

I really dont understand all this coding stuff, is anyone here who could be helpful to me and explain why this is? I would be really helpful.

This chinese article here ísnt only mixed chinese and english, i relly only understand "chinese" so nothing.

**Comment by XXXXRT666** [comment]
torch cu128

**Comment by hofbauermarketing** [comment]
> torch cu128

So when i install this than it should work? Thank your very much fpor your time and help! :)
