### ISSUE TITLE
开启GPT训练后一直卡住不动，Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/1，卡住不动

### ISSUE THREAD

**Issue by lcwzx** [RVC-Boss/GPT-SoVITS#234]
开启GPT训练后一直卡住不动，显示如下
Seed set to 1234
Using 16bit Automatic Mixed Precision (AMP)
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
<All keys matched successfully>
ckpt_path: None
[rank: 0] Seed set to 1234
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/1

**Comment by RVC-Boss** [comment]
你是win10吗？之前有人尝试过老版win10会卡死，升级到最新版win10或者win11就解决了

**Comment by lcwzx** [comment]
我的系统是win10专业版

**Comment by so0125** [comment]
解决了吗？我的也出现了一样的问题，我是WIN10家庭版的，不是很想换系统，有什么办法可以解决。

**Comment by MarkerL** [comment]
我的win10专业版也不行...

**Comment by wanghuoling** [comment]
我的也出现这个问题，后面通过单步调试跟踪代码，发现是卡在了项目根目录的venv\Lib\site-packages\lightning_fabric\utilities\distributed.py中的第290行。把
torch.distributed.init_process_group(torch_distributed_backend, rank=global_rank, world_size=world_size, **kwargs)
改为 
torch.distributed.init_process_group(backend=torch_distributed_backend,init_method='tcp://localhost:23456', world_size=world_size, rank=global_rank) 
即可正常运行了。希望对也遇到这个问题的人有个帮助。

**Comment by RVC-Boss** [comment]
https://github.com/RVC-Boss/GPT-SoVITS/commit/59f35adad85815df27e9c6b33d420f5ebfd8376b
理论上该commit修复了楼主的问题。如果还不行试试楼上强制指定分布式地址localhost的方法。
