### ISSUE TITLE
搭载5070ti 显卡pytorch报错

### ISSUE THREAD

**Issue by someone114514** [RVC-Boss/GPT-SoVITS#2478]
D:\GPT-SoVITS-v2pro-20250604 (1)\GPT-SoVITS-v2pro-20250604\runtime\lib\site-packages\torch\cuda\__init__.py:173: UserWarning:
NVIDIA GeForce RTX 5070 Ti Laptop GPU with CUDA capability sm_120 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_61 sm_70 sm_75 sm_80 sm_86 sm_90 compute_37.
If you want to use the NVIDIA GeForce RTX 5070 Ti Laptop GPU GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
"D:\GPT-SoVITS-v2pro-20250604 (1)\GPT-SoVITS-v2pro-20250604\runtime\python.exe" -s GPT_SoVITS/s2_train_v3_lora.py --config "D:\GPT-SoVITS-v2pro-20250604 (1)\GPT-SoVITS-v2pro-20250604\TEMP/tmp_s2.json"
INFO:LIJITAO:{'train': {'log_interval': 100, 'eval_interval': 500, 'seed': 1234, 'epochs': 2, 'learning_rate': 0.0001, 'betas': [0.8, 0.99], 'eps': 1e-09, 'batch_size': 1, 'fp16_run': True, 'lr_decay': 0.999875, 'segment_size': 20480, 'init_lr_ratio': 1, 'warmup_epochs': 0, 'c_mel': 45, 'c_kl': 1.0, 'text_low_lr_rate': 0.4, 'grad_ckpt': False, 'pretrained_s2G': 'GPT_SoVITS/pretrained_models/gsv-v4-pretrained/s2Gv4.pth', 'pretrained_s2D': 'GPT_SoVITS/pretrained_models/gsv-v4-pretrained/s2Dv4.pth', 'if_save_latest': True, 'if_save_every_weights': True, 'save_every_epoch': 1, 'gpu_numbers': '0', 'lora_rank': '32'}, 'data': {'max_wav_value': 32768.0, 'sampling_rate': 32000, 'filter_length': 2048, 'hop_length': 640, 'win_length': 2048, 'n_mel_channels': 128, 'mel_fmin': 0.0, 'mel_fmax': None, 'add_blank': True, 'n_speakers': 300, 'cleaned_text': True, 'exp_dir': 'logs/LIJITAO'}, 'model': {'inter_channels': 192, 'hidden_channels': 192, 'filter_channels': 768, 'n_heads': 2, 'n_layers': 6, 'kernel_size': 3, 'p_dropout': 0.1, 'resblock': '1', 'resblock_kernel_sizes': [3, 7, 11], 'resblock_dilation_sizes': [[1, 3, 5], [1, 3, 5], [1, 3, 5]], 'upsample_rates': [10, 8, 2, 2, 2], 'upsample_initial_channel': 512, 'upsample_kernel_sizes': [16, 16, 8, 2, 2], 'n_layers_q': 3, 'use_spectral_norm': False, 'gin_channels': 512, 'semantic_frame_rate': '25hz', 'freeze_quantizer': True, 'version': 'v4'}, 's2_ckpt_dir': 'logs/LIJITAO', 'content_module': 'cnhubert', 'save_weight_dir': 'SoVITS_weights_v4', 'name': 'LIJITAO', 'version': 'v4', 'pretrain': None, 'resume_step': None}
INFO:torch.distributed.distributed_c10d:Added key: store_based_barrier_key:1 to store for rank: 0
INFO:torch.distributed.distributed_c10d:Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 1 nodes.
phoneme_data_len: 10
wav_data_len: 100
100%|█████████████████████████████████████████████████████████████████████████████| 100/100 [00:00<00:00, 14269.74it/s]
skipped_phone:  0 , skipped_dur:  0
total left:  100
INFO:LIJITAO:loaded pretrained GPT_SoVITS/pretrained_models/gsv-v4-pretrained/s2Gv4.pth
loaded pretrained GPT_SoVITS/pretrained_models/gsv-v4-pretrained/s2Gv4.pth <All keys matched successfully>
start training from epoch 1
  0%|                                                                                           | 0/90 [00:00<?, ?it/s]Traceback (most recent call last):
  File "D:\GPT-SoVITS-v2pro-20250604 (1)\GPT-SoVITS-v2pro-20250604\GPT_SoVITS\s2_train_v3_lora.py", line 379, in <module>
    main()
  File "D:\GPT-SoVITS-v2pro-20250604 (1)\GPT-SoVITS-v2pro-20250604\GPT_SoVITS\s2_train_v3_lora.py", line 61, in main
    mp.spawn(
  File "D:\GPT-SoVITS-v2pro-20250604 (1)\GPT-SoVITS-v2pro-20250604\runtime\lib\site-packages\torch\multiprocessing\spawn.py", line 239, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "D:\GPT-SoVITS-v2pro-20250604 (1)\GPT-SoVITS-v2pro-20250604\runtime\lib\site-packages\torch\multiprocessing\spawn.py", line 197, in start_processes
    while not context.join():
  File "D:\GPT-SoVITS-v2pro-20250604 (1)\GPT-SoVITS-v2pro-20250604\runtime\lib\site-packages\torch\multiprocessing\spawn.py", line 149, in join
    raise ProcessExitedException(
torch.multiprocessing.spawn.ProcessExitedException: process 0 terminated with exit code 3221225620

**Comment by someone114514** [comment]
"D:\GPT-SoVITS-v2pro-20250604 (1)\GPT-SoVITS-v2pro-20250604\runtime\python.exe" -s GPT_SoVITS/s2_train.py --config "D:\GPT-SoVITS-v2pro-20250604 (1)\GPT-SoVITS-v2pro-20250604\TEMP/tmp_s2.json"
INFO:LIJITAO:{'train': {'log_interval': 100, 'eval_interval': 500, 'seed': 1234, 'epochs': 8, 'learning_rate': 0.0001, 'betas': [0.8, 0.99], 'eps': 1e-09, 'batch_size': 6, 'fp16_run': True, 'lr_decay': 0.999875, 'segment_size': 20480, 'init_lr_ratio': 1, 'warmup_epochs': 0, 'c_mel': 45, 'c_kl': 1.0, 'text_low_lr_rate': 0.4, 'grad_ckpt': False, 'pretrained_s2G': 'GPT_SoVITS/pretrained_models/v2Pro/s2Gv2Pro.pth', 'pretrained_s2D': 'GPT_SoVITS/pretrained_models/v2Pro/s2Dv2Pro.pth', 'if_save_latest': True, 'if_save_every_weights': True, 'save_every_epoch': 4, 'gpu_numbers': '0', 'lora_rank': '32'}, 'data': {'max_wav_value': 32768.0, 'sampling_rate': 32000, 'filter_length': 2048, 'hop_length': 640, 'win_length': 2048, 'n_mel_channels': 128, 'mel_fmin': 0.0, 'mel_fmax': None, 'add_blank': True, 'n_speakers': 300, 'cleaned_text': True, 'exp_dir': 'logs/LIJITAO'}, 'model': {'inter_channels': 192, 'hidden_channels': 192, 'filter_channels': 768, 'n_heads': 2, 'n_layers': 6, 'kernel_size': 3, 'p_dropout': 0.0, 'resblock': '1', 'resblock_kernel_sizes': [3, 7, 11], 'resblock_dilation_sizes': [[1, 3, 5], [1, 3, 5], [1, 3, 5]], 'upsample_rates': [10, 8, 2, 2, 2], 'upsample_initial_channel': 512, 'upsample_kernel_sizes': [16, 16, 8, 2, 2], 'n_layers_q': 3, 'use_spectral_norm': False, 'gin_channels': 1024, 'semantic_frame_rate': '25hz', 'freeze_quantizer': True, 'version': 'v2Pro'}, 's2_ckpt_dir': 'logs/LIJITAO', 'content_module': 'cnhubert', 'save_weight_dir': 'SoVITS_weights_v2Pro', 'name': 'LIJITAO', 'version': 'v2Pro', 'pretrain': None, 'resume_step': None}
INFO:torch.distributed.distributed_c10d:Added key: store_based_barrier_key:1 to store for rank: 0
INFO:torch.distributed.distributed_c10d:Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 1 nodes.
Traceback (most recent call last):
  File "D:\GPT-SoVITS-v2pro-20250604 (1)\GPT-SoVITS-v2pro-20250604\GPT_SoVITS\s2_train.py", line 684, in <module>
    main()
  File "D:\GPT-SoVITS-v2pro-20250604 (1)\GPT-SoVITS-v2pro-20250604\GPT_SoVITS\s2_train.py", line 61, in main
    mp.spawn(
  File "D:\GPT-SoVITS-v2pro-20250604 (1)\GPT-SoVITS-v2pro-20250604\runtime\lib\site-packages\torch\multiprocessing\spawn.py", line 239, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "D:\GPT-SoVITS-v2pro-20250604 (1)\GPT-SoVITS-v2pro-20250604\runtime\lib\site-packages\torch\multiprocessing\spawn.py", line 197, in start_processes
    while not context.join():
  File "D:\GPT-SoVITS-v2pro-20250604 (1)\GPT-SoVITS-v2pro-20250604\runtime\lib\site-packages\torch\multiprocessing\spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "D:\GPT-SoVITS-v2pro-20250604 (1)\GPT-SoVITS-v2pro-20250604\runtime\lib\site-packages\torch\multiprocessing\spawn.py", line 69, in _wrap
    fn(i, *args)
  File "D:\GPT-SoVITS-v2pro-20250604 (1)\GPT-SoVITS-v2pro-20250604\GPT_SoVITS\s2_train.py", line 90, in run
    train_dataset = TextAudioSpeakerLoader(hps.data, version=hps.model.version)
  File "D:\GPT-SoVITS-v2pro-20250604 (1)\GPT-SoVITS-v2pro-20250604\GPT_SoVITS\module\data_utils.py", line 58, in __init__
    for _ in range(max(2, int(min_num / leng))):
ZeroDivisionError: division by zero

**Comment by manfred-exz** [comment]
从文件夹名来看，你应该是下错包了。有提供50系专用的包，GPT-SoVITS-v2pro-20250604-nvidia50

**Comment by someone114514** [comment]
谢谢，解决了

**Comment by bollywood4u** [comment]
what is the resolution of this issue. i have the same issue. I have tried multiple versions of pytorch with cuda128 and get same error
