### ISSUE TITLE
[Bug Report] RuntimeError: "no kernel image is available" on new NVIDIA GPUs (e.g., RTX 5090 / sm_120)

### ISSUE THREAD

**Issue by eymenongelsama** [RVC-Boss/GPT-SoVITS#2514]
Hello GPT-SoVITS Team,
First of all, thank you for this incredible project. I'm very excited to get it running.
I am encountering a RuntimeError related to CUDA compatibility when trying to run inference on a new generation NVIDIA GPU. I've followed the setup instructions meticulously, but it seems the current PyTorch binaries do not yet support the architecture of the latest GPUs.
System Information:
Operating System: Windows 11
Python Version: 3.10 (within a Conda environment)
GPU: NVIDIA GeForce RTX 5090 Laptop GPU
CUDA Capability: sm_120
Problem Description:
The application launches successfully, and the WebUI is accessible. However, when I attempt to generate audio, the process fails with the following error, right after the embedding layer in the model:

RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

This error is preceded by a warning at startup, which correctly identifies the core issue:

UserWarning: 
NVIDIA GeForce RTX 5090 Laptop GPU with CUDA capability sm_120 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_50 sm_60 sm_61 sm_70 sm_75 sm_80 sm_86 sm_90.

Steps I've Taken to Troubleshoot:
I have already tried to resolve this by upgrading PyTorch to the latest available versions, including the nightly builds, but it appears that even the newest pre-release binaries do not yet include support for sm_120.

The command I used to install the latest PyTorch was:

pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu121

Unfortunately, this did not resolve the incompatibility warning or the runtime error.
Question and Potential Solutions:
Is there a recommended PyTorch version or a custom build that supports newer GPU architectures like sm_120 that you are aware of?
As a temporary workaround, I was able to get the inference to run by forcing the device to CPU mode (by editing device = "cpu"). This works, but it is naturally very slow. Is there a more elegant way to fall back to CPU only for the specific operations that are failing on the GPU, or is a full CPU fallback the only option for now?
Are there any plans to update the project's dependencies to align with PyTorch versions that will eventually support these new GPUs?
This seems to be a forward-compatibility issue as new hardware becomes available. Any guidance or suggestions you could provide would be greatly appreciated. I believe other users with new-generation hardware will soon face the same challenge.
Thank you for your time and for developing this amazing tool.
Best regards. :)

**Comment by RVC-Boss** [comment]
install pytorch>=2.7 with cu>=128

**Comment by eymenongelsama** [comment]
pip install -U https://huggingface.co/w-e-w/torch-2.6.0-cu128.nv/resolve/main/torch-2.6.0%2Bcu128.nv-cp310-cp310-win_amd64.whl





its special for blackwell architecture, it worked for me!

**Comment by teneous** [comment]
I have the same issue. Here is my config.
```
GPT-SoVITS-v2pro-20250604-nvidia50
torch 2.8 
cuda cu128
gpu RTX 5090
```
And this is my err log
`onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Slice node. Name:'Slice_12' Status Message: CUDA error cudaErrorNoKernelImageForDevice:no kernel image is available for execution on the device`

**Comment by hjj-lmx** [comment]
> 我也遇到了同样的问题。这是我的配置。
> 
> ```
> GPT-SoVITS-v2pro-20250604-nvidia50
> torch 2.8 
> cuda cu128
> gpu RTX 5090
> ```
> 
> 这是我的错误日志 `onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Slice node. Name:'Slice_12' Status Message: CUDA error cudaErrorNoKernelImageForDevice:no kernel image is available for execution on the device`

如何解决的

**Comment by teneous** [comment]
> > 我也遇到了同样的问题。这是我的配置。
> > ```
> > GPT-SoVITS-v2pro-20250604-nvidia50
> > torch 2.8 
> > cuda cu128
> > gpu RTX 5090
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 这是我的错误日志 `onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Slice node. Name:'Slice_12' Status Message: CUDA error cudaErrorNoKernelImageForDevice:no kernel image is available for execution on the device`
> 
> 如何解决的

我最终使用了 `2.7.0+cu128` 的组合，然后可以正常work了
