### ISSUE TITLE
GPU not detected using Rocm 7.2 Pytorch on Windows system (Cuda is True)

### ISSUE THREAD

**Issue by Crazysunday727** [RVC-Boss/GPT-SoVITS#2743]
So I currently finished setting up Rocm 7.2 with Pytorch on my windows system. When I run the command python -c "import torch; print(torch.cuda.is_available())" I do get True as a return. So I'm curious if GPT-Sovits is not updated to handle Rocm 7.2 with Pytorch yet or am I missing an extra step here in order for it to detect my GPU?

I have a AMD Radeon RX 9070 XT 
The 26.1.1 graphics driver
Using Python 3.12 
I followed the AMD website and Rocm and Pytorch are both installed based on there instructions. I've search every where but only find answers for Linux machines and python 3.9

**Comment by spordniar** [comment]
Try vosen/ZLUDA Version 6-preview.63

**Comment by spordniar** [comment]
I got it working eventually with some struggle.

Here I attach my venv's requirements.txt FYR, not sure if everything is needed but recommend to just have all these installed.

For the AMD specialized drivers such as triton / torch / Jinja2, you can find it from AMD's rocm nightly repo, just google them, or you can follow this link and install ROCm / PyTorch / ONNX under WSL: https://rocm.docs.amd.com/projects/radeon-ryzen/en/docs-7.2/docs/install/installrad/wsl/howto_wsl.html
(can't remember if ONNX is required or not though)

absl-py==2.4.0
accelerate==1.13.0
aiofiles==23.2.1
aiohappyeyeballs==2.6.1
aiohttp==3.13.3
aiosignal==1.4.0
aliyun-python-sdk-core==2.16.0
aliyun-python-sdk-kms==2.16.5
annotated-doc==0.0.4
annotated-types==0.7.0
antlr4-python3-runtime==4.9.3
anyio==4.13.0
argbind==0.3.9
asttokens==3.0.1
attrs==26.1.0
audioread==3.1.0
av==17.0.0
baize==0.23.1
brotli==1.2.0
budoux==0.8.0
cachetools==7.0.5
certifi==2026.2.25
cffi==2.0.0
chardet==7.3.0
charset-normalizer==3.4.6
click==8.3.1
cn2an==0.5.23
coloredlogs==15.0.1
colorlog==6.10.1
contourpy==1.3.3
crcmod==1.7
cryptography==46.0.6
ctranslate2==4.7.1
cycler==0.12.1
datasets==2.18.0
decorator==5.2.1
descript-audio-codec==1.0.0
descript-audiotools==0.7.2
dill==0.3.8
Distance==0.1.3
dnspython==2.8.0
docstring_parser==0.17.0
editdistance==0.8.1
einops==0.8.2
einx==0.4.2
ema-pytorch==0.7.9
email-validator==2.3.0
executing==2.2.1
fast-langdetect==1.0.0
fastapi==0.135.2
fastapi-cli==0.0.24
fastapi-cloud-cli==0.15.1
fastar==0.9.0
faster-whisper==1.2.1
fasttext-predict==0.9.2.4
ffmpeg-python==0.2.0
ffmpy==1.0.0
filelock==3.25.2
fire==0.7.1
flatbuffers==25.12.19
flatten-dict==0.4.2
fonttools==4.62.1
frozendict==2.4.7
frozenlist==1.8.0
fsspec==2024.2.0
funasr==1.0.27
future==1.0.0
g2p-en==2.1.0
g2pk2==0.0.3
gitdb==4.0.12
GitPython==3.1.46
gradio==6.10.0
gradio_client==2.4.0
groovy==0.1.2
grpcio==1.78.0
h11==0.16.0
hf-gradio==0.3.0
hf-xet==1.4.2
httpcore==1.0.9
httptools==0.7.1
httpx==0.28.1
huggingface_hub==0.36.2
humanfriendly==10.0
hydra-core==1.3.2
idna==3.11
importlib_resources==6.5.2
inflect==7.5.0
ipython==9.11.0
ipython_pygments_lexers==1.1.1
jaconv==0.5.0
jamo==0.4.1
jedi==0.19.2
jieba==0.42.1
jieba_fast==0.53
Jinja2 @ https://rocm.nightlies.amd.com/v2-staging/gfx120X-all/jinja2-3.1.6-py3-none-any.whl#sha256=85ece4451f492d0c13c5dd7c13a64681a86afae63a5f347908daf103ce6d2f67
jmespath==0.10.0
joblib==1.5.3
julius==0.2.7
kaldiio==2.18.1
kiwisolver==1.5.0
ko-pron==1.3
kui==1.14.0
lazy-loader==0.5
librosa==0.10.2
lightning==2.6.1
lightning-utilities==0.15.3
llvmlite==0.46.0
loguru==0.7.3
loralib==0.1.2
Markdown==3.10.2
markdown-it-py==4.0.0
markdown2==2.5.5
MarkupSafe==2.1.5
matplotlib==3.10.8
matplotlib-inline==0.2.1
mdurl==0.1.2
modelscope==1.17.1
more-itertools==10.8.0
mpmath==1.3.0
msgpack==1.1.2
multidict==6.7.1
multiprocess==0.70.16
natsort==8.4.0
networkx==3.6.1
nltk==3.9.4
numba==0.64.0
numpy==1.26.4
nvidia-cublas-cu12==12.8.4.1
nvidia-cuda-cupti-cu12==12.8.90
nvidia-cuda-nvrtc-cu12==12.8.93
nvidia-cuda-runtime-cu12==12.8.90
nvidia-cudnn-cu12==9.10.2.21
nvidia-cufft-cu12==11.3.3.83
nvidia-cufile-cu12==1.13.1.3
nvidia-curand-cu12==10.3.9.90
nvidia-cusolver-cu12==11.7.3.90
nvidia-cusparse-cu12==12.5.8.93
nvidia-cusparselt-cu12==0.7.1
nvidia-nccl-cu12==2.27.3
nvidia-nvjitlink-cu12==12.8.93
nvidia-nvtx-cu12==12.8.90
omegaconf==2.3.0
onnxruntime-migraphx==1.24.2
onnxruntime-rocm==1.22.2.post1
openai-whisper==20250625
OpenCC==1.2.0
opencc-python-reimplemented==0.1.7
orjson==3.11.7
ormsgpack==1.12.2
oss2==2.19.1
packaging==26.0
pandas==2.3.3
parso==0.8.6
peft==0.17.1
pexpect==4.9.0
pillow==10.4.0
platformdirs==4.9.4
pooch==1.9.0
proces==0.1.7
prompt_toolkit==3.0.52
propcache==0.4.1
protobuf==3.20.3
psutil==7.2.2
ptyprocess==0.7.0
pure_eval==0.2.3
pyarrow==23.0.1
pyarrow-hotfix==0.7
PyAudio==0.2.14
pybind11==3.0.2
pycparser==3.0
pycryptodome==3.23.0
pydantic==2.9.2
pydantic-extra-types==2.11.1
pydantic-settings==2.13.1
pydantic_core==2.23.4
pydub==0.25.1
Pygments==2.19.2
pyloudnorm==0.2.0
pynndescent==0.6.0
pyopenjtalk==0.4.1
pyparsing==3.3.2
pypinyin==0.55.0
pyrootutils==1.0.4
pystoi==0.4.1
python-dateutil==2.9.0.post0
python-dotenv==1.2.2
python-fire==0.1.0
python-mecab-ko==1.3.7
python-mecab-ko-dic==2.1.1.post2
python-multipart==0.0.22
pytorch-lightning==2.6.1
pytorch-wpe==0.0.1
pytz==2026.1.post1
PyYAML==6.0.3
randomname==0.2.1
regex==2026.2.28
requests==2.33.0
resampy==0.4.3
rich==14.3.3
rich-toolkit==0.19.7
rignore==0.7.6
robust-downloader==0.0.2
rotary-embedding-torch==0.8.9
ruff==0.15.7
safehttpx==0.1.7
safetensors==0.7.0
scikit-learn==1.8.0
scipy==1.17.1
semantic-version==2.10.0
sentencepiece==0.2.1
sentry-sdk==2.56.0
setuptools==82.0.1
shellingham==1.5.4
silero-vad==6.2.1
six==1.17.0
smmap==5.0.3
soundfile==0.13.1
soxr==1.0.0
split-lang==2.1.1
stack-data==0.6.3
starlette==0.52.1
sympy==1.14.0
tensorboard==2.20.0
tensorboard-data-server==0.7.2
tensorboardX==2.6.4
termcolor==3.3.0
threadpoolctl==3.6.0
tiktoken==0.12.0
ToJyutping==3.2.0
tokenizers==0.21.4
tomlkit==0.12.0
torch @ torch-2.9.1%2Brocm7.2.0.lw.git7e1940d4-cp312-cp312-linux_x86_64.whl#sha256=199ba10a8b8b5a7eef64985bf87a41f0f4b28d49b1b861aa2768f6c5314c9b86
torch-complex==0.4.4
torch-stoi==0.2.3
torchaudio @ torchaudio-2.9.0%2Brocm7.2.0.gite3c6ee2b-cp312-cp312-linux_x86_64.whl#sha256=cf78fd7774ca6187254a63051d07c46ab1f4bbd5a47e64b8d372d3c58e52979a
torchmetrics==1.5.0
torchvision @ torchvision-0.24.0%2Brocm7.2.0.gitb919bd0c-cp312-cp312-linux_x86_64.whl#sha256=071667fd26e9af4e05127eabc572015d1f629e318096abc854b6c946f346359b
tqdm==4.67.3
traitlets==5.14.3
transformers==4.50.0
triton @ triton-3.5.1%2Brocm7.2.0.gita272dfa8-cp312-cp312-linux_x86_64.whl#sha256=73d435248c3a207fec6f5a7a2aba631c7079a61230ce4aaa8cde02e800024b47
typeguard==4.5.1
typer==0.24.1
typing-inspection==0.4.2
typing_extensions==4.15.0
tzdata==2025.3
umap-learn==0.5.11
urllib3==2.6.3
uvicorn==0.42.0
uvloop==0.22.1
vector-quantize-pytorch==1.14.24
wandb==0.25.0
watchfiles==1.1.1
wcwidth==0.6.0
websockets==12.0
Werkzeug==3.1.7
wheel==0.46.3
wordsegment==1.3.1
x-transformers==2.17.8
xxhash==3.6.0
yarl==1.23.0
zstandard==0.25.0

**Comment by spordniar** [comment]
As for the modification of python files under GPT-SoVITS (yes you need to tweak the python files a little), some of the files won't torch.load due to compatibility with AMD's torch version, you may leverage alternative library - soundfile to make things work.

Lines with no +/- means you just need to find the line, and append whatever comes next with the + signs, but add them without the + signs. Lines with - means you find the line, remove them, and add whatever comes next with the + signs but add them without the + signs.

1. GPT_SoVITS/TTS_infer_pack/TTS.py:

```
 import torchaudio
+import soundfile as sf
+import numpy as np

     def _get_ref_spec(self, ref_audio_path):
-        raw_audio, raw_sr = torchaudio.load(ref_audio_path)
+        raw_audio, raw_sr = sf.read(ref_audio_path)
+        if len(raw_audio.shape) == 1:
+            raw_audio = torch.from_numpy(raw_audio).float().unsqueeze(0)
+        else:
+            raw_audio = torch.from_numpy(raw_audio.T).float()
```

2. GPT_SoVITS/prepare_datasets/2-get-sv.py:

```
 import torchaudio
+import soundfile as sf
+import numpy as np

def name2go(wav_name, wav_path):
-    wav32k, sr0 = torchaudio.load(wav_path)
-    assert sr0 == 32000
+    data, sr0 = sf.read(wav_path)
+    if len(data.shape) == 1:
+        wav32k = torch.from_numpy(data).float().unsqueeze(0)
+    else:
+        wav32k = torch.from_numpy(data.T).float()
```

Let me know if you have any questions, and I will try my best to help you guys out.

**Comment by barleyeater** [comment]
> As for the modification of python files under GPT-SoVITS (yes you need to tweak the python files a little), some of the files won't torch.load due to compatibility with AMD's torch version, you may leverage alternative library - soundfile to make things work.
> 
> Lines with no +/- means you just need to find the line, and append whatever comes next with the + signs, but add them without the + signs. Lines with - means you find the line, remove them, and add whatever comes next with the + signs but add them without the + signs.
> 
> 1. GPT_SoVITS/TTS_infer_pack/TTS.py:
> 
> ```
>  import torchaudio
> +import soundfile as sf
> +import numpy as np
> 
>      def _get_ref_spec(self, ref_audio_path):
> -        raw_audio, raw_sr = torchaudio.load(ref_audio_path)
> +        raw_audio, raw_sr = sf.read(ref_audio_path)
> +        if len(raw_audio.shape) == 1:
> +            raw_audio = torch.from_numpy(raw_audio).float().unsqueeze(0)
> +        else:
> +            raw_audio = torch.from_numpy(raw_audio.T).float()
> ```
> 
> 2. GPT_SoVITS/prepare_datasets/2-get-sv.py:
> 
> ```
>  import torchaudio
> +import soundfile as sf
> +import numpy as np
> 
> def name2go(wav_name, wav_path):
> -    wav32k, sr0 = torchaudio.load(wav_path)
> -    assert sr0 == 32000
> +    data, sr0 = sf.read(wav_path)
> +    if len(data.shape) == 1:
> +        wav32k = torch.from_numpy(data).float().unsqueeze(0)
> +    else:
> +        wav32k = torch.from_numpy(data.T).float()
> ```
> 
> Let me know if you have any questions, and I will try my best to help you guys out.

**Worked for me on Fedora 44 following the dependency list above and making the changes in the .py files. inference_webui.py was still broken for me however, I was getting this error:**

> OSError: Could not load this library: /home/user/path/to/GPT-SoVITS/gptSovitsVenv/lib/python3.10/ site-packages/torchcodec/libtorchcodec_image.so

I made these changes to inference_webui.py:
```
  import torchaudio
+import soundfile as sf
+import numpy as np

def get_spepc(hps, filename, dtype, device, is_v2pro=False):
    sr1 = int(hps.data.sampling_rate)
  - audio, sr0 = torchaudio.load(filename)
  + audio, sr0 = sf.read(filename)
  + if len (audio.shape) == 1:
  +     audio = torch.from_numpy(audio).float().unsqueeze(0)
  + else:
  +     audio = torch.from_numpy(audio.T).float()
```
and
```
else:
            refer, audio_tensor = get_spepc(hps, ref_wav_path, dtype, device)
            phoneme_ids0 = torch.LongTensor(phones1).to(device).unsqueeze(0)
            phoneme_ids1 = torch.LongTensor(phones2).to(device).unsqueeze(0)
            fea_ref, ge = vq_model.decode_encp(prompt.unsqueeze(0), phoneme_ids0, refer)
          - ref_audio, sr = torchaudio.load(ref_wav_path)
          +  audio, sr = sf.read(ref_wav_path)
          +  if len(audio.shape) == 1:
          +     ref_audio = torch.from_numpy(audio).float().unqueeze(0)
          +  else:
          +     ref_audio = torch.from_numpy(audio.T).float()

```
spordniar i love you

**Comment by luckykevvv** [comment]
I found the same issue when running on rocm 7.2, the issue of torchaudio load have been fixed pr #2831  . See if it solves your problem
