### ISSUE TITLE
无法使用 faster whisper

### ISSUE THREAD

**Issue by aixiaodewugege** [RVC-Boss/GPT-SoVITS#697]
报错：Could not load library libcudnn_ops_infer.so.8. Error: libcudnn_ops_infer.so.8: cannot open shared object file: No such file or directory

**Comment by YANG627** [comment]
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/54615630/977ee5dc-170d-47e9-ae70-bfc6a107e0a3)
me too, I encounter this issue with my nvidia driver version is 535
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/54615630/ec93642a-dc5e-43f7-8d9e-7889e80e1685)
I did research in google, https://github.com/SYSTRAN/faster-whisper/issues/516 
It seem demonstrate I need cuda11.8, but i using the official docker image to run the repos, and checked the pytorch has cuda11.8 with it
![image](https://github.com/RVC-Boss/GPT-SoVITS/assets/54615630/4c45eb28-2a9b-4fb5-a448-1420726940d0)
so now, I have no idea to deal with the issue. Anyone helps?

**Comment by barryhunt** [comment]
the same to you

**Comment by Dako2** [comment]
+1

**Comment by XXXXRT666** [comment]
export LD_LIBRARY_PATH

**Comment by Oyiyi** [comment]
+1

**Comment by YANG627** [comment]
I installed a Cuda with version 11.8 on my Ubuntu and switched to it, this problem has been solved. Another problem is core dump occurs in inferencing, the solution is to run the below code in the terminal before using faster whisper
export LD_LIBRARY_PATH=`python3 -c 'import os; import nvidia.cublas.lib; import nvidia.cudnn.lib; print(os.path.dirname(nvidia.cublas.lib.__file__) + ":" + os.path.dirname(nvidia.cudnn.lib.__file__))'`
Hope the messages will be helpful to you.
